In [2]:
import json
import pandas as pd

In [3]:
# set pandas to display all the columns
pd.set_option('display.max_columns', None)

In [4]:
# load json file
with open('weather_data.json') as json_file:
    data = json.load(json_file)

In [5]:
# Extract the 'data' part from the json file and transform it into a DataFrame
df = pd.DataFrame(data['data'])

# display top 10 rows of dataframe
df.head(10)

,app_temp,azimuth,clouds,datetime,dewpt,dhi,dni,elev_angle,ghi,h_angle,pod,precip,pres,revision_status,rh,slp,snow,solar_rad,temp,timestamp_local,timestamp_utc,ts,uv,vis,weather,wind_dir,wind_gust_spd,wind_spd
0,10.6,0.7,100,2022-01-01:05,8.2,0,0,-72.3,0,None,n,0.00,1008,final,85,1013,0.0,0,10.6,2022-01-01T00:00:00,2022-01-01T05:00:00,1641013200,0.0,13,"{'description': 'Overcast clouds', 'code': 804...",195,3.6,1.6
1,10.6,40.5,100,2022-01-01:06,8.2,0,0,-68.1,0,None,n,0.00,1008,final,85,1013,0.0,0,10.6,2022-01-01T01:00:00,2022-01-01T06:00:00,1641016800,0.0,14,"{'description': 'Overcast clouds', 'code': 804...",175,3.6,2.0
2,10.6,64.3,100,2022-01-01:07,8.9,0,0,-59.1,0,None,n,0.50,1008,final,89,1013,0.0,0,10.6,2022-01-01T02:00:00,2022-01-01T07:00:00,1641020400,0.0,11,"{'description': 'Overcast clouds', 'code': 804...",150,3.6,1.6
3,10.6,79.0,100,2022-01-01:08,8.2,0,0,-48.3,0,None,n,0.00,1006,final,85,1012,0.0,0,10.6,2022-01-01T03:00:00,2022-01-01T08:00:00,1641024000,0.0,11,"{'description': 'Overcast clouds', 'code': 804...",130,3.6,2.6
4,10.0,89.8,100,2022-01-01:09,8.8,0,0,-37.0,0,None,n,0.00,1006,final,92,1011,0.0,0,10.0,2022-01-01T04:00:00,2022-01-01T09:00:00,1641027600,0.0,11,"{'description': 'Overcast clouds', 'code': 804...",150,4.4,2.1
5,10.0,99.1,100,2022-01-01:10,9.4,0,0,-25.7,0,None,n,0.00,1006,final,96,1011,0.0,0,10.0,2022-01-01T05:00:00,2022-01-01T10:00:00,1641031200,0.0,11,"{'description': 'Overcast clouds', 'code': 804...",150,4.4,2.0
6,10.6,108.0,100,2022-01-01:11,9.4,0,0,-14.6,0,None,n,0.25,1005,final,92,1010,0.0,0,10.6,2022-01-01T06:00:00,2022-01-01T11:00:00,1641034800,0.0,6,"{'description': 'Overcast clouds', 'code': 804...",150,4.8,2.1
7,10.6,117.1,100,2022-01-01:12,9.4,0,0,-4.2,0,None,n,0.50,1005,final,92,1010,0.0,0,10.6,2022-01-01T07:00:00,2022-01-01T12:00:00,1641038400,0.0,8,"{'description': 'Overcast clouds', 'code': 804...",165,4.0,2.0
8,10.6,126.9,100,2022-01-01:13,10.0,38,326,5.5,59,None,d,0.75,1004,final,96,1010,0.0,42,10.6,2022-01-01T08:00:00,2022-01-01T13:00:00,1641042000,0.4,5,"{'description': 'Light rain', 'code': 500, 'ic...",185,4.0,2.1
9,11.1,138.1,100,2022-01-01:14,9.9,66,588,13.8,198,None,d,1.00,1005,final,92,1009,0.0,79,11.1,2022-01-01T09:00:00,2022-01-01T14:00:00,1641045600,0.4,5,"{'description': 'Light rain', 'code': 500, 'ic...",200,4.0,1.5

In [6]:
# Convert the DataFrame to a list of dictionaries
data = df.to_dict(orient='records')

cleaned_data = []

# Iterate over each entry
for entry in data:
    # Extract the desired columns
    cleaned_entry = {
        'temp': entry['temp'],
        'datetime': entry['datetime'],
        'weather': entry['weather']
    }
    cleaned_data.append(cleaned_entry)

# Write the cleaned data to a new JSON file
with open('output.json', 'w') as file:
    json.dump(cleaned_data, file)

In [7]:
# Read the JSON file
with open('output.json') as file:
    data = json.load(file)

# Create a DataFrame from the JSON data
df = pd.DataFrame(data)

# Display the top 10 rows of the DataFrame
df.head(10)

   temp       datetime                                            weather
0  10.6  2022-01-01:05  {'description': 'Overcast clouds', 'code': 804...
1  10.6  2022-01-01:06  {'description': 'Overcast clouds', 'code': 804...
2  10.6  2022-01-01:07  {'description': 'Overcast clouds', 'code': 804...
3  10.6  2022-01-01:08  {'description': 'Overcast clouds', 'code': 804...
4  10.0  2022-01-01:09  {'description': 'Overcast clouds', 'code': 804...
5  10.0  2022-01-01:10  {'description': 'Overcast clouds', 'code': 804...
6  10.6  2022-01-01:11  {'description': 'Overcast clouds', 'code': 804...
7  10.6  2022-01-01:12  {'description': 'Overcast clouds', 'code': 804...
8  10.6  2022-01-01:13  {'description': 'Light rain', 'code': 500, 'ic...
9  11.1  2022-01-01:14  {'description': 'Light rain', 'code': 500, 'ic...

In [8]:
df['weather_description'] = df['weather'].apply(lambda x: x['description'])

# Display the updated DataFrame
df.head(10)

,temp,datetime,weather,weather_description
0,10.6,2022-01-01:05,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
1,10.6,2022-01-01:06,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
2,10.6,2022-01-01:07,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
3,10.6,2022-01-01:08,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
4,10.0,2022-01-01:09,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
5,10.0,2022-01-01:10,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
6,10.6,2022-01-01:11,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
7,10.6,2022-01-01:12,"{'description': 'Overcast clouds', 'code': 804...",Overcast clouds
8,10.6,2022-01-01:13,"{'description': 'Light rain', 'code': 500, 'ic...",Light rain
9,11.1,2022-01-01:14,"{'description': 'Light rain', 'code': 500, 'ic...",Light rain

In [9]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].nunique()

print("Number of unique values in 'weather_description' column:", unique_values)

Number of unique values in 'weather_description' column: 17

In [10]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].unique().tolist()

print("List of unique values in 'weather_description' column:")
print(unique_values)

List of unique values in 'weather_description' column:
['Overcast clouds', 'Light rain', 'Heavy rain', 'Fog', 'Clear Sky', 'Broken clouds', 'Scattered clouds', 'Flurries', 'Snow', 'Light snow', 'Moderate rain', 'Haze', 'Mix snow/rain', 'Freezing rain', 'Heavy snow', 'Few clouds', 'Thunderstorm with heavy rain']

In [11]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].unique().tolist()

In [12]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].unique().tolist()

# Group the unique values based on specific categories
snow_group = [value for value in unique_values if 'snow' in value.lower()]
flurries_group = [value for value in unique_values if 'flurries' in value.lower()]
haze_group = [value for value in unique_values if 'haze' in value.lower()]
clouds_group = [value for value in unique_values if 'clouds' in value.lower()]

print("Grouping of unique values in 'weather_description' column:")
print("Snow Group:", snow_group)
print("Flurries Group:", flurries_group)
print("Haze Group:", haze_group)
print("Clouds Group:", clouds_group)

Grouping of unique values in 'weather_description' column:
Snow Group: ['Snow', 'Light snow', 'Mix snow/rain', 'Heavy snow']
Flurries Group: ['Flurries']
Haze Group: ['Haze']
Clouds Group: ['Overcast clouds', 'Broken clouds', 'Scattered clouds', 'Few clouds']

In [13]:
# Group the unique values based on specific categories
clouds_group = [value for value in unique_values if 'clouds' in value.lower() or 'haze' in value.lower()]
snow_group = [value for value in unique_values if 'snow' in value.lower()]
flurries_group = [value for value in unique_values if 'flurries' in value.lower()]

print("Grouping of unique values in 'weather_description' column:")
print("Clouds Group:", clouds_group)
print("Snow Group:", snow_group)
print("Flurries Group:", flurries_group)

Grouping of unique values in 'weather_description' column:
Clouds Group: ['Overcast clouds', 'Broken clouds', 'Scattered clouds', 'Haze', 'Few clouds']
Snow Group: ['Snow', 'Light snow', 'Mix snow/rain', 'Heavy snow']
Flurries Group: ['Flurries']

In [14]:

# Group the unique values based on specific categories
clouds_group = [value for value in unique_values if 'clouds' in value.lower() or 'haze' in value.lower()]
snow_group = [value for value in unique_values if 'snow' in value.lower() or ('flurries' in value.lower() and 'mix snow/rain' not in value.lower())]
print("Grouping of unique values in 'weather_description' column:")
print("Clouds Group:", clouds_group)
print("Snow Group (including Flurries):", snow_group)

Grouping of unique values in 'weather_description' column:
Clouds Group: ['Overcast clouds', 'Broken clouds', 'Scattered clouds', 'Haze', 'Few clouds']
Snow Group (including Flurries): ['Flurries', 'Snow', 'Light snow', 'Mix snow/rain', 'Heavy snow']

In [15]:
# Update the 'weather_description' column with the desired categories
df.loc[df['weather_description'].str.contains('snow', case=False), 'weather_description'] = 'Snow'
df.loc[df['weather_description'].str.contains('flurries', case=False), 'weather_description'] = 'Snow'
df.loc[df['weather_description'].str.contains('clouds|haze', case=False), 'weather_description'] = 'Cloudy'

# Verify the updated 'weather_description' column
print(df['weather_description'].unique().tolist())

['Cloudy', 'Light rain', 'Heavy rain', 'Fog', 'Clear Sky', 'Snow', 'Moderate rain', 'Freezing rain', 'Thunderstorm with heavy rain']

In [16]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].nunique()

print("Number of unique values in 'weather_description' column:", unique_values)

Number of unique values in 'weather_description' column: 9

In [17]:
# Assuming you have the 'weather_description' column in the DataFrame
unique_values = df['weather_description'].unique().tolist()

print("List of unique values in 'weather_description' column:")
print(unique_values)

List of unique values in 'weather_description' column:
['Cloudy', 'Light rain', 'Heavy rain', 'Fog', 'Clear Sky', 'Snow', 'Moderate rain', 'Freezing rain', 'Thunderstorm with heavy rain']

# app_temp: Apparent/"Feels Like" temperature (default Celsius)
# azimuth: Solar azimuth angle (degrees).
# clouds: cloud coverage (%)
# datetime: Date UTC (YYYY-MM-DD:HH).
# dewpt: Dew point (default Celsius)
# dhi: Diffuse horizontal solar irradiance (W/m^2) [Clear Sky]
# dni: Direct normal solar irradiance (W/m^2) [Clear Sky]
# elev_angle: Solar elevation angle (degrees)
# ghi: Global horizontal solar irradiance (W/m^2) [Clear Sky]
# h_angle: [DEPRECATED] Solar hour angle (degrees)
# pod: Part of the day (d = day / n = night)
# precip: Accumulated liquid equivalent precipitation (default mm)
# pres: Pressure (mb)
# revision_status: Data revision status - interim (subject to revisions) or final
# rh: Relative humidity (%)
# slp: Sea level pressure (mb)
# snow: Accumulated snowfall (default mm)
# solar_rad: Estimated Solar Radiation (W/m^2)
# temp: Temperature
# timestamp_local: Timestamp at Local time
# timestamp_utc: Timestamp at UTC time
# ts: Timestamp (Unix Timestamp)
# uv: UV Index (0-11+)
# vis: Visibility (default KM)
# weather:  {
icon: Weather icon code.
code: Weather code.
description: Text weather description.
} 
# wind_dir: Wind direction (degrees)
# wind_gust_spd: Wind gust speed (Default m/s)
# wind_spd: Wind speed (Default m/s)

# app_temp: Apparent/"Feels Like" temperature (default Celsius)
# datetime: Date UTC (YYYY-MM-DD:HH).
# pod: Part of the day (d = day / n = night)
# precip: Accumulated liquid equivalent precipitation (default mm)
# rh: Relative humidity (%)
# snow: Accumulated snowfall (default mm)
# solar_rad: Estimated Solar Radiation (W/m^2)
# temp: Temperature
# vis: Visibility (default KM)
# weather:  {
icon: Weather icon code.
code: Weather code.
description: Text weather description.
} 
# wind_spd: Wind speed (Default m/s)